### ISSUE TITLE
2nd Call/ Event Listener for second User selection (Park Selection) 

### ISSUE THREAD

**Issue by mwambaugh** [mwambaugh/collaborativeAPIstudy#47]
State > Park Name > Local Storage > End Points 

"event listener looking for that value and specific array with that name then pulled description for that array... "
button is the "name" ,  event listener needs to be  targeted to  user selection ... position in the array 
then getIMAGE, then then getDESCRIPTION 

**IDEAS:** FOR loop to look at the index, looking for the user selected PARK, then going to specific destination to then append the element. 

**IDEAS:** select state > GET parks array (objects) by state name > array of Parks  === OBJ Array > IF /ELSE array of parks  (object => object.parkCode === Olympic) {} 

**IDEAS :** Options class list from all states, from the options class will pop. the the park is chosen it would.   

**NICK :** When you select the state and get the park, use the park code, not the name, OR park name AND park code ... then show information...  
Clean the response for the first API, save that data, second would sub to the cleaned data,
It might be easier to make the second user selection into buttons, drop downs are not as responsive as you think.  
THE BEST WAY is to create another data structure...
WHAT we can do here is to ... (can we add parts to what we had... how to add another event listener) NEED to be able to save this to another variable) (CREATE another...) might be able to do what R/A...    

_creating a data structure with a has map 
create a data structure 
using the data response_

**END OF NICK's NOTES**

**Comment by hkim84** [comment]
completed
